[package]
name = "mead_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
libbpf-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.38.0", features = ["full"] }
